export const pokemonTypes = [
  { name: "choose", value: 0 },
  { name: "normal", value: 1 },
  { name: "fighting", value: 2 },
  { name: "flying", value: 3 },
  { name: "poison", value: 4 },
  { name: "ground", value: 5 },
  { name: "rock", value: 6 },
  { name: "bug", value: 7 },
  { name: "ghost", value: 8 },
  { name: "steel", value: 9 },
  { name: "fire", value: 10 },
  { name: "water", value: 11 },
  { name: "grass", value: 12 },
  { name: "electric", value: 13 },
  { name: "psychic", value: 14 },
  { name: "ice", value: 15 },
  { name: "dragon", value: 16 },
  { name: "dark", value: 17 },
  { name: "fairy", value: 18 },
  { name: "unknown", value: 19 },
  { name: "shadow", value: 20 },
];
